# Generated by Django 3.2.4 on 2021-06-29 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='Gender')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('state', models.CharField(blank=True, max_length=25)),
                ('city', models.CharField(blank=True, max_length=25)),
                ('zip_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='zip code')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True)),
                ('profile_image', models.ImageField(default='/static/images/default_profile_image.jpg', upload_to='profile_pic')),
                ('qualification', models.CharField(max_length=50, verbose_name='Qualification')),
                ('charges', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Charges Per Class')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='Gender')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('state', models.CharField(blank=True, max_length=25)),
                ('city', models.CharField(blank=True, max_length=25)),
                ('zip_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='zip code')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True)),
                ('profile_image', models.ImageField(default='/static/images/default_profile_image.jpg', upload_to='profile_pic')),
                ('grade', models.CharField(choices=[('J', 'Junior'), ('M', 'Middle'), ('H', 'Highschool'), ('S', 'Senior')], max_length=1, verbose_name='Grade')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('parent_name', models.CharField(max_length=50, verbose_name='Parent Name')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='Gender')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('state', models.CharField(blank=True, max_length=25)),
                ('city', models.CharField(blank=True, max_length=25)),
                ('zip_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='zip code')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True)),
                ('profile_image', models.ImageField(default='/static/images/default_profile_image.jpg', upload_to='profile_pic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
